version: '3.5'

services:
  metricbeat:
    image: "${metricbeat_image_full}"
    # https://github.com/docker/swarmkit/issues/1951
#    hostname: "{{.Node.Hostname}}-metricbeat"
    user: root
    networks:
      - apps_prodnetwork
    volumes:
      - "${app_stack_conf_dir}/metricbeat:/metricbeat:ro"
      - metricbeat:/usr/share/metricbeat/data
      - /var/run/docker.sock:/var/run/docker.sock
#      - /proc:/hostfs/proc:ro
#      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
#      - /:/hostfs:ro
    command: ["--strict.perms=false", "--path.config", "/metricbeat"]
#    environment:
#      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}
#      - KIBANA_HOST=${KIBANA_HOST:-node1}
#      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
#      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
#    # disable strict permission checks
#    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
#    deploy:
#      mode: global
#
networks:
  apps_prodnetwork:
    external: true
#    # https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html#monitoring-host
#    name: host
#networks:
#  beat:
#    driver: bridge
#    driver_opts:
#      com.docker.network.driver.mtu: 1450
#
volumes:
  metricbeat:
