version: '3.5'

services:
  heartbeat:
    image: "${heartbeat_image_full}"
#    hostname: "{{.Node.Hostname}}-heartbeat"
    user: root
    networks:
      - beat
    volumes:
      - "${app_stack_conf_dir}/heartbeat:/heartbeat:ro"
      - heartbeat:/usr/share/heartbeat/data
    command: ["--strict.perms=false", "--path.config", "/heartbeat"]

  metricbeat:
    image: "${metricbeat_image_full}"
    # https://github.com/docker/swarmkit/issues/1951
#    hostname: "{{.Node.Hostname}}-metricbeat"
    user: root
    networks:
      - beat
    volumes:
      - "${app_stack_conf_dir}/metricbeat:/metricbeat:ro"
      - metricbeat:/usr/share/metricbeat/data
      - /var/run/docker.sock:/var/run/docker.sock
#      - /proc:/hostfs/proc:ro
#      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
#      - /:/hostfs:ro
    command: ["--strict.perms=false", "--path.config", "/metricbeat"]
#    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
#    environment:
#      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}
#      - KIBANA_HOST=${KIBANA_HOST:-node1}
#      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
#      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
#
#networks:
#  elastic:
#    external: true
#    # https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html#monitoring-host
#    name: host
networks:
  beat:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  metricbeat:
  heartbeat:
